# =======================
# General
fullscreen=no
keep-open=yes                   # don't close after finished the video
save-position-on-quit=yes
image-display-duration=inf
autocreate-playlist=same

# =======================
# Miscellaneous
osc=no
gpu-api=opengl                  # opengl somehow init faster than vulken
input-default-bindings=no

# Theme
include=~~/theme.conf
